scss_files: 'app/assets/stylesheets/**/*.css.scss'

exclude: 'app/assets/stylesheets/plugins/**'

linters:
  BorderZero:
    enabled: false

  Indentation:
    severity: warning
    width: 4
    
  PropertySortOrder:
      enabled: false
      
  ColorVariable:
    enabled: false
    
  ZeroUnit:
    enabled: false
    
  HexNotation:
    enabled: true
    style: uppercase
    
  NestingDepth:
    enabled: false
    
  SelectorDepth:
    enabled: false